### PR TITLE
Make pre-commit-hook print diff instead of modify it

### PR DESCRIPTION
**Pull request by foriequal0**

### CODE REVIEW

**Comment by foriequal0** [comment]
I've rebased to the master after https://github.com/CodeChain-io/codechain-sdk-python/pull/34

**Comment by posgnu** [comment]
Why we have to do this? I think just modifying is more convenient.

**Comment by foriequal0** [comment]
It is useful to patch automatically when we trigger it manually from CLI, however, it would be better to show diff when it is called on CI.
I think I can utilize this option https://pre-commit.com/#confining-hooks-to-run-at-certain-stages

**Comment by foriequal0** [comment]
We can use different config files https://github.com/pre-commit/pre-commit/issues/1146
I've made another config file for the CI.

**Comment by posgnu** [comment]
I see.

**Pull request merged**
