### PR TITLE
Run lint

### PR DESCRIPTION
**Pull request by posgnu**
This is what I get after running `pre-commit run --all-files`

### CODE REVIEW

**Comment by posgnu** [comment]
I am still figuring out why this difference occurs.

**Comment by foriequal0** [comment]
We are using `stable` for `black` https://github.com/CodeChain-io/codechain-sdk-python/blob/master/.pre-commit-config.yaml#L3
They move `stable` tag 🤔 . Anyway, the current stable one is 19.10b0.
Can you check what version do you use?

**Comment by posgnu** [comment]
` pre-commit autoupdate` this command did not help me.

**Comment by foriequal0** [comment]
Would you try to add python 3.6, 3.7 matrix to the lint like I did in the unit test job?

**Comment by foriequal0** [comment]
I've added: https://github.com/CodeChain-io/codechain-sdk-python/pull/51

**Comment by foriequal0** [comment]
I found the reason. 
https://github.com/asottile/reorder_python_imports depends on https://github.com/asottile/aspy.refactor_imports.
It doesn’t know whether dataclass was backported, (which is builtin after 3.7, but not for 3.6) so it classify dataclass as a third-party library. `reorder_python_imports` separates third-parties and builtins.

**Pull request closed without merging**
